# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('time', models.DurationField(null=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_input_one', models.IntegerField(default=0)),
                ('sensor_input_two', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='exercise.Exercise')),
            ],
        ),
    ]
