# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
