# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_auto_20170527_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
