# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20170527_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise',
            new_name='states',
        ),
    ]
