# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('coefficient', models.IntegerField(null=True)),
                ('good_standing_time', models.DurationField(null=True)),
                ('bad_standing_time', models.DurationField(null=True)),
                ('total_time', models.DurationField(null=True)),
                ('done_training', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='days', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
