# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('coefficient', models.IntegerField(null=True)),
                ('good_standing_time', models.DurationField()),
                ('bad_standing_time', models.DurationField()),
                ('total_time', models.DurationField()),
                ('done_training', models.BooleanField(default=False)),
            ],
        ),
    ]
