# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0002_day_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='bad_standing_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='good_standing_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='total_time',
            field=models.DurationField(null=True),
        ),
    ]
